#!/bin/bash
# Download all Docker container icons to /boot/config/docker-icons/
DIR="/boot/config/docker-icons"
mkdir -p "$DIR"

download() {
    local name="$1" url="$2"
    local ext="${url##*.}"
    ext="${ext:0:3}"
    local dest="$DIR/${name}.${ext}"
    if [ -f "$dest" ] && [ "$(stat -c%s "$dest" 2>/dev/null)" -gt 100 ]; then
        echo "  EXISTS $name"
        return 0
    fi
    if wget -q -O "$dest" "$url" 2>/dev/null && [ -f "$dest" ] && [ "$(stat -c%s "$dest")" -gt 100 ]; then
        echo "  OK $name"
        return 0
    else
        rm -f "$dest"
        echo "  FAIL $name"
        return 1
    fi
}

DI="https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png"

download "adguard-home" "https://raw.githubusercontent.com/SiwatINC/unraid-ca-repository/master/icons/adguard.png"
download "comixed" "$DI/komga.png"
download "gitea" "$DI/gitea.png"
download "gluetunvpn" "https://raw.githubusercontent.com/qdm12/gluetun/master/doc/logo_256.png"
download "namer" "$DI/tautulli.png"
download "npm" "$DI/nginx-proxy-manager.png"
download "plex" "$DI/plex.png"
download "redis" "$DI/redis.png"
download "actual-budget" "$DI/actual-budget.png"
download "authentik" "$DI/authentik.png"
download "alertmanager" "$DI/alertmanager.png"
download "audiobookshelf" "$DI/audiobookshelf.png"
download "postgres" "$DI/postgresql.png"
download "blackbox-exporter" "$DI/prometheus.png"
download "bookstack" "$DI/bookstack.png"
download "mariadb" "$DI/mariadb.png"
download "cadvisor" "$DI/cadvisor.png"
download "calibre" "$DI/calibre.png"
download "calibre-web" "$DI/calibre-web.png"
download "crowdsec" "$DI/crowdsec.png"
download "docker" "$DI/docker.png"
download "davis" "$DI/davis.png"
download "donetick" "$DI/donetick.png"
download "dozzle" "$DI/dozzle.png"
download "fasten" "$DI/fasten-health.png"
download "flaresolverr" "$DI/flaresolverr.png"
download "fleet" "$DI/fleetdm.png"
download "mysql" "$DI/mysql.png"
download "grafana" "$DI/grafana.png"
download "grocy" "$DI/grocy.png"
download "guacamole" "$DI/guacamole.png"
download "headwind-mdm" "$DI/headwind-mdm.png"
download "homepage" "$DI/homepage.png"
download "homebox" "$DI/homebox.png"
download "homechart" "https://raw.githubusercontent.com/candiddev/homechart/main/hugo/static/homechart.png"
download "immich" "$DI/immich.png"
download "it-tools" "$DI/it-tools.png"
download "kapowarr" "https://raw.githubusercontent.com/JPDVM2014/icons/refs/heads/main/kapowarr.png"
download "kavita" "$DI/kavita.png"
download "kopia" "$DI/kopia.png"
download "loki" "$DI/loki.png"
download "ntfy" "$DI/ntfy.png"
download "mealie" "$DI/mealie.png"
download "mylar3" "$DI/mylar.png"
download "n8n" "$DI/n8n.png"
download "paperless-ngx" "$DI/paperless-ngx.png"
download "peppermint" "$DI/peppermint.png"
download "prometheus" "$DI/prometheus.png"
download "prowlarr" "$DI/prowlarr.png"
download "qbittorrent" "$DI/qbittorrent.png"
download "radarr" "$DI/radarr.png"
download "romm" "$DI/romm.png"
download "sabnzbd" "$DI/sabnzbd.png"
download "seerr" "$DI/seerr.png"
download "sonarr" "$DI/sonarr.png"
download "speedtest-tracker" "$DI/speedtest-tracker.png"
download "stash" "$DI/stash.png"
download "stirling-pdf" "$DI/stirling-pdf.png"
download "tdarr" "$DI/tdarr.png"
download "ubooquity" "$DI/ubooquity.png"
download "uptime-kuma" "$DI/uptime-kuma.png"
download "vikunja" "$DI/vikunja.png"
download "webcheck" "$DI/web-check.png"
download "whisparr" "$DI/whisparr.png"
download "yarnl" "https://raw.githubusercontent.com/titandrive/yarnl/main/public/icon-512.png"
download "youtube-dl" "$DI/youtube.png"
download "portal" "$DI/homepage.png"
download "mailrise" "$DI/ntfy.png"

echo ""
echo "Total icons: $(ls -1 $DIR | wc -l)"
echo "Directory: $DIR"
